name: Deploy Static Files With Nginx

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add EC2 Host Key
        env:
          host: ${{ secrets.REMOTE_SERVER }}
          PEM_KEY: ${{ secrets.PEM_KEY}}
        run: |
          mkdir -p ~/.ssh
          echo "$PEM_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $host >> ~/.ssh/known_hosts  

      # SCP로 서버로 전송
      - name: Deploy to server
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}  # PEM 키를 GitHub Secrets에 저장
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.REMOTE_SERVER }}
          key: ${{ secrets.PEM_KEY }}
          target_path: ${{ secrets.target_path }}
          nginx_conf_path : ${{ secrets.NGINX_CONF_FILE_PATH }}
        run: |
          echo "${{ secrets.PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r main/* $username@$host:$target_path
          scp -i private_key.pem main/resources/nginx_config/* $username@$host:$nginx_conf_path

      - name: Move ranking-quiz.conf to nginx sites-enabled
        env:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.REMOTE_SERVER }}
        run: |
          ssh -i private_key.pem $username@$host "sudo mv /resources/nginx_config/ranking-quiz.conf /etc/nginx/sites-enabled/default"

      - name: Nginx restart
        env:
          PEM_KEY: ${{ secrets.PEM_KEY }}  # PEM 키를 GitHub Secrets에 저장
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.REMOTE_SERVER }}
          key: ${{ secrets.PEM_KEY }}
        run: |
          echo "${{ secrets.PEM_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -i private_key.pem "$username@$host" "
            sudo systemctl restart nginx
          "
          echo 'key를 제거합니다.'
          ssh-keygen -R $host